default_platform(:android)

platform :android do
  desc "Build Flutter Release Android App Bundle (AAB)"
  lane :build_aab do
    sh("cd ../.. && flutter clean && flutter pub get && make clean-gen && flutter build appbundle --release")
  end

  desc "Build Flutter Release APK"
  lane :build_apk do
    sh("cd ../.. && flutter clean && flutter pub get && make clean-gen && flutter build apk --release")
  end

  desc "Deploy to Google Play Internal Sharing / Internal Track"
  lane :internal do
    build_aab
    upload_to_play_store(
      track: "internal",
      release_status: ENV["PLAY_STORE_RELEASE_STATUS"] || "completed",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy to Google Play Closed Testing (Alpha)"
  lane :alpha do
    build_aab
    upload_to_play_store(
      track: "alpha",
      release_status: ENV["PLAY_STORE_RELEASE_STATUS"] || "completed",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy to Google Play Open Testing (Beta)"
  lane :beta do
    build_aab
    upload_to_play_store(
      track: "beta",
      release_status: ENV["PLAY_STORE_RELEASE_STATUS"] || "completed",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Deploy to Google Play Production"
  lane :production do
    build_aab
    upload_to_play_store(
      track: "production",
      release_status: ENV["PLAY_STORE_RELEASE_STATUS"] || "completed",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: false,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Promote Internal Track to Production Track"
  lane :promote_internal_to_production do
    upload_to_play_store(
      track: "internal",
      track_promote_to: "production",
      release_status: "completed",
      skip_upload_metadata: false,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
